### ISSUE TITLE
Wrong path in README.md?

### ISSUE THREAD

**Issue by MatthewPinheiro** [duosecurity/duo_nodejs#19]
Hello,

I'm not great with npm or the require function at all to be perfectly honest, but I was having issues with the following line specified in the README.md file:

`> const duo_web = require('duo_web');`

This results in an error finding the module. However, judging by the file structure of the node_modules folder after the installation (and also judging by the `npm install --save @duosecurity/duo_web` instruction), shouldn't the line actually be:

`> const duo_web = require('@duosecurity/duo_web');`

In addition, shouldn't `npm install global @duosecurity/duo_web` actually be `npm install --global @duosecurity/duo_web`?

Please let me know if there is something in the README I overlooked.

**Comment by JakePayton** [comment]
Thanks @MatthewPinheiro

**Comment by mschwager** [comment]
Good catch! We updated the package name in https://github.com/duosecurity/duo_nodejs/commit/d2692304e2be7efac4b108f38776d99bbe9843cc, but forgot to update the README :)

**Comment by mschwager** [comment]
Fixed by #20
