### ISSUE TITLE
Updating npm

### ISSUE THREAD

**Issue by ncknuna** [duosecurity/duo_nodejs#8]
It looks like the no changes have been pushed to npm in 3 years: https://www.npmjs.com/package/duo_web. 

Are there plans to push a more current version any time soon? or is there another way that this should be consumed?

**Comment by adrikim** [comment]
Hey Nathan,

Apologies for the late response, but yes, we're looking to see if we can release a newer version sometime in the future. I'm not sure about exactly when, but we're at least tracking this internally now so we don't forget.

Thanks for letting us know, and thanks for using Duo! :)

**Comment by DuoKristina** [comment]
Nathan,

You should be able to grab the master tarball from here, extract it, and use npm to install from the extracted download. That way you'll have more recent updates than available on npmjs.com.

**Comment by ncknuna** [comment]
@adrikim Yay, glad it's on your roadmap!

@DuoKristina Since we don't check in our node_modules/ directory, that won't be a super helpful approach for us unless I'm missing something. I can just reference this repo from package.json directly, or reference the tarball directly to work around this, but that just makes this an odd corner-case in our dependency management =/

**Comment by jaredmeakin** [comment]
Agreed. Same issue for me as well. Subscribing for updates to know when npm is updated. Thanks!

**Comment by mschwager** [comment]
Just released version `1.0.3` on NPM :+1:
